dist: xenial
language: scala

scala:
  - 2.12.9
  - 2.13.0

env:
  - TRAVIS_NODE_VERSION="12.5.0"

jdk:
  - openjdk8
  - openjdk11

install:
  - rm -rf ~/.nvm &&
    git clone https://github.com/nvm-sh/nvm.git ~/.nvm &&
    (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) &&
    source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION

script:
  - sbt ++$TRAVIS_SCALA_VERSION scalafmtSbtCheck scalafmtCheck test:scalafmtCheck clean current/doc core/doc test

before_cache:
  - rm -fv $HOME/.ivy2/.sbt.ivy.lock
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.coursier   -name "*.lock"               -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.coursier
    - $HOME/.sbt/boot

